services:
  
  postgres:
    container_name: postgres_container
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "127.0.0.1:5444:5432"
    networks:
      - postgres
    restart: unless-stopped

  storage:
    container_name: seaweed_container
    image: chrislusf/seaweedfs
    command: server -s3
    ports:
      - "8333:8333"
    volumes:
      - seaweed:/data


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  seaweed: